# Generated by Django 3.1.2 on 2020-10-11 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioAccProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_value', models.PositiveSmallIntegerField(choices=[(1, 'Накопление во всех звеньях'), (2, 'Накопление в нескольких звеньях'), (3, 'Накопление в одном из звеньев'), (4, 'Нет накопления')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CancerogProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_value', models.PositiveSmallIntegerField(choices=[(1, 'Доказана для человека'), (2, 'Доказана для животных'), (3, 'Есть вероят- ность для животных'), (4, 'Неканцероген (доказано)')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HazardClassProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_type', models.PositiveSmallIntegerField(choices=[(5, 'Класс опасности в воде'), (6, 'Класс опасности в рабочей зоне'), (7, 'Класс опасности в атмосферном воздухе'), (8, 'Класс опасности в почве')])),
                ('prop_value', models.PositiveSmallIntegerField(choices=[(1, '1 класс'), (2, '2 класс'), (3, '3 класс'), (4, '4 класс')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HazardValueProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_type', models.PositiveSmallIntegerField(choices=[(1, 'ПДК (ОДК) в почве, мг/кг'), (2, 'ПДК (ОДУ) в воде, мг/л'), (3, 'ПДК рабочей зоны, мг/м^3'), (4, 'ПДК среднесуточная или максимально разовая (ОБУВ), мг/м^3'), (9, 'DL50 перорально, мг/кг'), (10, 'CL50, мг/м^3'), (12, 'Lg (S, мг/л/ПДКв)'), (13, 'Lg (Снас, мг/м^3/ПДКр. з)'), (14, 'ПДКвр, мг/л'), (15, 'DL50skin, мг/кг '), (16, 'CL50w, мг/л/96 ч '), (17, 'Lg (Снас, мг/м^3/ПДКсс/мр)'), (18, 'КВИО'), (19, 'Log Kow (октанол/вода)'), (23, 'ПДКпп в продуктах питания')])),
                ('prop_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LiteratureSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latexpart', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MutagenProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_value', models.PositiveSmallIntegerField(choices=[(1, 'Обнаружена'), (2, 'Есть возможность проявления для человека'), (3, 'Есть возможность проявления для животных'), (4, 'Отсутствует (доказано) ')])),
                ('literature_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemcomponent.literaturesource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersistProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_value', models.PositiveSmallIntegerField(choices=[(1, 'Образование болеетоксичных продуктов, в т. ч. обладающих отдаленными эффектами или новыми свойствами'), (2, 'Образование продуктов с более выраженным влиянием др. критериев вредности'), (3, 'Образование продуктов, токсичность которых близка к токсичности исходного вещества'), (4, 'Образование менее токсичных продуктов')])),
                ('literature_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemcomponent.literaturesource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WasteComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_type', models.CharField(choices=[('S', 'Неопасное W=10^6'), ('O', 'Органическое'), ('I', 'Неорганическое')], default='S', max_length=1, verbose_name='Вещество')),
                ('bio_acc_prop', models.ManyToManyField(related_name='bio_acc_prop', through='chemcomponent.BioAccProp', to='chemcomponent.LiteratureSource')),
                ('cancerog_prop', models.ManyToManyField(related_name='cancerog_prop', through='chemcomponent.CancerogProp', to='chemcomponent.LiteratureSource')),
                ('hazard_class_prop', models.ManyToManyField(related_name='hazard_class_prop', through='chemcomponent.HazardClassProp', to='chemcomponent.LiteratureSource')),
                ('hazard_value_prop', models.ManyToManyField(related_name='hazard_value_prop', through='chemcomponent.HazardValueProp', to='chemcomponent.LiteratureSource')),
                ('mutagen_prop', models.ManyToManyField(related_name='mutagen_prop', through='chemcomponent.MutagenProp', to='chemcomponent.LiteratureSource')),
                ('persist_prop', models.ManyToManyField(related_name='persist_prop', through='chemcomponent.PersistProp', to='chemcomponent.LiteratureSource')),
            ],
        ),
        migrations.AddField(
            model_name='persistprop',
            name='waste_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemcomponent.wastecomponent'),
        ),
        migrations.AddField(
            model_name='mutagenprop',
            name='waste_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemcomponent.wastecomponent'),
        ),
        migrations.AddField(
            model_name='hazardvalueprop',
            name='literature_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemcomponent.literaturesource'),
        ),
        migrations.AddField(
            model_name='hazardvalueprop',
            name='waste_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemcomponent.wastecomponent'),
        ),
        migrations.AddField(
            model_name='hazardclassprop',
            name='literature_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemcomponent.literaturesource'),
        ),
        migrations.AddField(
            model_name='hazardclassprop',
            name='waste_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemcomponent.wastecomponent'),
        ),
        migrations.AddField(
            model_name='cancerogprop',
            name='literature_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemcomponent.literaturesource'),
        ),
        migrations.AddField(
            model_name='cancerogprop',
            name='waste_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemcomponent.wastecomponent'),
        ),
        migrations.AddField(
            model_name='bioaccprop',
            name='literature_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemcomponent.literaturesource'),
        ),
        migrations.AddField(
            model_name='bioaccprop',
            name='waste_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemcomponent.wastecomponent'),
        ),
    ]
