# Generated by Django 3.1.2 on 2020-10-12 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('litsource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Название')),
                ('chemical_type', models.CharField(choices=[('S', 'Неопасное W=10^6'), ('O', 'Органическое'), ('I', 'Неорганическое')], default='S', max_length=1, verbose_name='Тип')),
                ('w_value', models.FloatField(blank=True, null=True, verbose_name='W - Коэффициента степени опасности компонента (если известен - указание источника обязательно)')),
                ('lit_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_components', to='litsource.literaturesource', verbose_name='Если задан W, то обязателен источник литературы')),
            ],
            options={
                'verbose_name': 'Компонент отхода',
                'verbose_name_plural': 'Компоненты отхода',
            },
        ),
    ]
