# Generated by Django 3.1.2 on 2020-10-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litsource', '0001_initial'),
        ('chemcomponent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastecomponent',
            name='lit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_components', to='litsource.literaturesource', verbose_name='Источник литературы (если задано числовое значение W, то обязателен)'),
        ),
    ]
