# Generated by Django 3.1.2 on 2020-10-11 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemcomponent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hazardvalueprop',
            options={'verbose_name': 'Числовое свойство', 'verbose_name_plural': 'Числовые свойства'},
        ),
        migrations.AlterModelOptions(
            name='hazardvaluetype',
            options={'verbose_name': 'Числовой параметр', 'verbose_name_plural': 'Числовые параметры'},
        ),
        migrations.AlterModelOptions(
            name='literaturesource',
            options={'verbose_name': 'Литературный источник', 'verbose_name_plural': 'Литературные источники'},
        ),
        migrations.RemoveField(
            model_name='hazardclassprop',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='hazardvalueprop',
            name='importance',
        ),
        migrations.AddField(
            model_name='hazardclasstype',
            name='importance',
            field=models.PositiveSmallIntegerField(default=2, unique=True, verbose_name='Важность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hazardvaluetype',
            name='importance',
            field=models.PositiveSmallIntegerField(default=5, unique=True, verbose_name='Важность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hazardclassprop',
            name='literature_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_props', to='chemcomponent.literaturesource', verbose_name='Литература'),
        ),
    ]
