# Generated by Django 3.1.2 on 2020-10-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemcomponent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecomponent',
            name='name',
            field=models.CharField(default='dsadsa', max_length=400),
            preserve_default=False,
        ),
    ]
