# Generated by Django 3.1.3 on 2020-12-04 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemcomponent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecomponent',
            name='cas_number',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(regex='\x08[1-9]{1}[0-9]{1,6}-\\d{2}-\\d\x08')], verbose_name='Регистрационный номер CAS'),
        ),
    ]
