# Generated by Django 3.1.3 on 2020-12-08 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemcomponent', '0002_wastecomponent_cas_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastecomponent',
            name='w_value',
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='x_value',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(4.0)], verbose_name='X - относительный параметр опасности компонента отхода для окружающей среды (если известен - указание источника обязательно)'),
        ),
        migrations.AlterField(
            model_name='wastecomponent',
            name='cas_number',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='CAS код для вещества в формате 1111-11-1', regex='\\b[1-9]{1}[0-9]{1,6}-\\d{2}-\\d\\b')], verbose_name='Регистрационный номер CAS'),
        ),
    ]
