# Generated by Django 3.1.3 on 2020-12-13 16:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litsource', '0004_auto_20201208_1908'),
        ('chemcomponent', '0004_auto_20201208_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastecomponent',
            name='land_concentration',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000000.0)], verbose_name='Максимальная фоновая концентрация в почвах (мг/кг) (если известно - указание источника обязательно)'),
        ),
        migrations.AlterField(
            model_name='wastecomponent',
            name='lit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_components', to='litsource.literaturesource', verbose_name='Источник литературы (если задано числовое значение X или фоновая концентрация, то обязателен)'),
        ),
        migrations.AlterField(
            model_name='wastecomponent',
            name='other_names',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Другие названия (через точку с запятой)'),
        ),
    ]
