# Generated by Django 3.1.3 on 2020-12-17 14:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litsource', '0004_auto_20201208_1908'),
        ('chemcomponent', '0005_auto_20201213_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastecomponent',
            name='lit_source',
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='bpk5',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Биологическое потребление кислорода, выраженное в миллилитрах O2/л за 5 суток'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='bpk5_lit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bpk5', to='litsource.literaturesource', verbose_name='Источник литературы для БПК5 (если задан, то обязателен)'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='c_nasish',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Насыщающая концентрация вещества в воздухе при 20°С и нормальном давлении (мг/м^3)'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='c_nasish_lit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_nasish', to='litsource.literaturesource', verbose_name='Источник литературы для насыщающей концентрации вещества (если задана, то обязателен)'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='k_ow',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Коэффициент распределения в системе октанол/вода при 20°С'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='k_ow_lit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='k_ow', to='litsource.literaturesource', verbose_name='Источник литературы для K_ow (если задан, то обязателен)'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='land_concentration_lit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_concentration', to='litsource.literaturesource', verbose_name='Источник литературы для фоновой концентрации (если задана фоновая концентрация, то обязателен)'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='pdk_mr',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Предельно допустимая концентрация вещества максимально разовая в атмосферном воздухе населенных мест (мг/м^3)'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='pdk_mr_lit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdk_mr', to='litsource.literaturesource', verbose_name='Источник литературы для ПДКмр (если задан, то обязателен)'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='pdk_rz',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Предельно допустимая концентрация вещества в атмосферном воздухе рабочей зоны (мг/м^3)'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='pdk_rz_lit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdk_rz', to='litsource.literaturesource', verbose_name='Источник литературы для ПДКрз (если задан, то обязателен)'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='pdk_ss',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Предельно допустимая концентрация вещества среднесуточная в атмосферном воздухе населенных мест (мг/м^3)'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='pdk_ss_lit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdk_ss', to='litsource.literaturesource', verbose_name='Источник литературы для ПДКсс (если задан, то обязателен)'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='pdk_v',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Предельно допустимая концентрация вещества в воде водных объектов, используемых для целей питьевого и хозяйственно-бытового водоснабжения (мг/л)'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='pdk_v_lit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdk_v', to='litsource.literaturesource', verbose_name='Источник литературы для ПДКв (если задан, то обязателен)'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='s_rastv',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Растворимость компонента отхода (вещества) в воде при 20°С (мг/л)'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='s_rastv_lit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s_rastv', to='litsource.literaturesource', verbose_name='Источник литературы для растворимости компонента отхода (если задана, то обязателен)'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='x_value_lit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='x_value', to='litsource.literaturesource', verbose_name='Источник литературы для относительного параметра опаности (если задано числовое значение X, то обязателен)'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='xpk',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Химическое потребление кислорода ХПК, выраженное в миллилитрах O2/100 л'),
        ),
        migrations.AddField(
            model_name='wastecomponent',
            name='xpk_lit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xpk', to='litsource.literaturesource', verbose_name='Источник литературы для ХПК (если задан, то обязателен)'),
        ),
        migrations.AlterField(
            model_name='wastecomponent',
            name='land_concentration',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000.0)], verbose_name='Максимальная фоновая концентрация в почвах (мг/кг) (если известно - указание источника обязательно)'),
        ),
    ]
