# Generated by Django 3.1.3 on 2020-12-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemcomponent', '0006_auto_20201217_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastecomponent',
            name='k_ow',
        ),
        migrations.RemoveField(
            model_name='wastecomponent',
            name='k_ow_lit_source',
        ),
    ]
