# Generated by Django 3.1.4 on 2020-12-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('prikaz', 'Приказ'), ('gost', 'ГОСТ'), ('art', 'Статья')], default='art', max_length=10)),
                ('latexpart', models.TextField()),
                ('source_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Url cсылка на источник (при наличии)')),
                ('human_name', models.CharField(default='', max_length=200, verbose_name='Название для показа рядом со ссылками')),
            ],
            options={
                'verbose_name': 'Литературный источник',
                'verbose_name_plural': 'Литературные источники',
            },
        ),
    ]
