# Generated by Django 3.1.2 on 2020-10-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latexpart', models.TextField()),
            ],
            options={
                'verbose_name': 'Литературный источник',
                'verbose_name_plural': 'Литературные источники',
            },
        ),
    ]
