# Generated by Django 3.1.3 on 2020-11-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litsource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturesource',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Url cсылка на источник (при наличии)'),
        ),
        migrations.AlterField(
            model_name='literaturesource',
            name='source_type',
            field=models.CharField(choices=[('art', 'Статья'), ('gost', 'ГОСТ')], default='art', max_length=10),
        ),
    ]
