# Generated by Django 3.1.3 on 2020-12-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litsource', '0003_literaturesource_human_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaturesource',
            name='source_type',
            field=models.CharField(choices=[('prikaz', 'Приказ'), ('gost', 'ГОСТ'), ('art', 'Статья')], default='art', max_length=10),
        ),
    ]
