# Generated by Django 3.1.3 on 2020-11-26 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chemcomponent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcentrationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conc_value', models.FloatField()),
                ('conc_p', models.FloatField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concentrations', to='chemcomponent.wastecomponent')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WasteClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название отхода')),
                ('fkko', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код ФККО')),
                ('components', models.ManyToManyField(through='waste.ConcentrationClass', to='chemcomponent.WasteComponent')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='concentrationclass',
            name='waste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concentrations', to='waste.wasteclass'),
        ),
        migrations.AlterUniqueTogether(
            name='concentrationclass',
            unique_together={('waste', 'component')},
        ),
    ]
