# Generated by Django 3.1.3 on 2020-11-24 14:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemcomponent', '0003_auto_20201121_0931'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste', '0002_auto_20201013_2145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Concentration',
            new_name='ConcentrationClass',
        ),
    ]
