# Generated by Django 3.1.3 on 2020-12-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentprop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardcategorytype',
            name='short_name',
            field=models.CharField(default='', max_length=100, verbose_name='Короткое название'),
        ),
        migrations.AddField(
            model_name='hazardvaluetype',
            name='short_name',
            field=models.CharField(default='', max_length=100, verbose_name='Короткое название'),
        ),
    ]
