# Generated by Django 3.1.3 on 2020-11-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemcomponent', '0003_auto_20201121_0931'),
        ('componentprop', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hazardcategoryprop',
            unique_together={('waste_component', 'value_type')},
        ),
        migrations.AlterUniqueTogether(
            name='hazardvalueprop',
            unique_together={('waste_component', 'value_type')},
        ),
    ]
