# Generated by Django 3.1.3 on 2020-12-13 16:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemcomponent', '0005_auto_20201213_1945'),
        ('litsource', '0004_auto_20201208_1908'),
        ('componentprop', '0002_auto_20201202_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardComplexValueProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_float_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Числовое значение')),
                ('literature_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_complex_props', to='litsource.literaturesource', verbose_name='Литература')),
                ('value_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_complex_props', to='componentprop.hazardvaluetype')),
                ('waste_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_complex_props', to='chemcomponent.wastecomponent')),
            ],
            options={
                'verbose_name': 'Числовое свойство для комплексных вычислений типа Lg (S, мг/л / ПДКв, мг.л)',
                'verbose_name_plural': 'Числовые свойства для комплексных вычислений типа Lg (S, мг/л / ПДКв, мг.л)',
                'unique_together': {('waste_component', 'value_type')},
            },
        ),
    ]
