# Generated by Django 3.1.3 on 2020-12-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentprop', '0003_hazardcomplexvalueprop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardvalueprop',
            name='prop_float_value',
            field=models.FloatField(verbose_name='Числовое значение'),
        ),
        migrations.DeleteModel(
            name='HazardComplexValueProp',
        ),
    ]
